### ISSUE TITLE
Bootstrap a Golang REST API Project

### ISSUE THREAD

**Issue by MiguelMachado-dev** [forjadev/gun-organization#2]
As a part of our ongoing development efforts, we need to bootstrap a new project written in Golang. The core functionality of this project will be a REST API.

Here are the specific tasks that need to be addressed:

Project Initialization: Set up the initial project structure using Go modules. The structure should follow best practices for Golang project organization. Provide a clear README.md with instructions for cloning, installing dependencies, and running the project.

Dependency Management: Define the necessary dependencies for the project. This includes any libraries needed for creating the REST API, such as net/http or any other preferred frameworks like Gin or Echo. Configure these dependencies in the go.mod file.

Configuration of REST Endpoints: Set up a basic REST API structure in the main.go file. This should include at least one example each of a GET, POST, PUT, and DELETE request handler. These endpoints should return dummy data for now.

Testing: Create a basic unit test case for the REST endpoints using Go's built-in testing package.

**Comment by vinirossado** [comment]
If you desire, I can generate an illustrative framework using the Command Line Interface (CLI) I am currently developing, which we can either utilize as is or commence our project from it.

**Comment by vinirossado** [comment]
I am leveraging popular libraries such as Gin, Wire, Errors and so on.

**Comment by MiguelMachado-dev** [comment]
It's not time to work on this yet, and maybe we are going to build from scratch so other people can learn how to do it

**Comment by vinirossado** [comment]
Ah, ok.
