### ISSUE TITLE
[SPIKE] Extract members of a team from an organization

### ISSUE THREAD

**Issue by MiguelMachado-dev** [forjadev/gun-organization#5]
Identify how to get a list of all members inside a github organization's team.

For example:

In our organization we have the gungnir team, and inside of it we have several different members, we need to figure out how to programmatically get a list of all those members with their handles to use on other services.

**Comment by laracarvalho** [comment]
@MiguelMachado-dev the title seems unclear to me. Is it about removing someone from the org or returning data from someone inside a specific team? If the latter, [this api endpoint](https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members) does that.

**Comment by MiguelMachado-dev** [comment]
We need to figure out if there is a way to detect/find the member of a team.
For example, in the README we are classifying the members according to the team they are in, frontend or backend.

So not only do we need to update the README automatically, but also understand which team each user is in so we can separate them in the README.

**Comment by OtavioSC** [comment]
Using the code below, I got all members from Gungnir and set them to a text file using the GitHub API.
We can use many requests as we need (one for each team). As @laracarvalho mentioned, the API already has a solution for this.

```bash
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/{org-name}/teams/{team-name}/members >> test.txt
```

**Comment by junio256** [comment]
> set them to a text file using the GitHub API...

Right, but it makes use of Github CLI which probably have to authenticate as a user to get those functionalities
I think all we need is to register our API on github to get one TOKEN and make requests

**Comment by OtavioSC** [comment]
Yes, but authentication is necessary for all instances if we use the org's endpoint because to get member's data is needed to have owner permission or something similar. This was just an example of Github API behavior.

**Comment by junio256** [comment]
Instead, the ideal would be use this type of request and rely only on our API functions instead of handling files or arguments

```go
func handler(ctx *Context) {
    client := &http.Client{}
    
    // brief example
    team := ctx.Param("team")
    baseURL := fmt.Sprintf("https://api.github.com/orgs/forjadev/teams/%v/members", team)
    
    // Create an HTTP request with custom headers
    req, err := http.NewRequest("GET", baseURL, nil)
    if err != nil { return }
    
    // GitHub request headers recommendation
    req.Header.Add("Accept", "application/vnd.github+json")
    req.Header.Add("Authorization", fmt.Sprintf("Bearer %v", env.GITHUB_API_TOKEN))
    req.Header.Add("X-GitHub-Api-Version", "2022-11-28")
    
    resp, err := client.Do(req)
    // [...]
}
```

**Comment by jbiers** [comment]
I see we have already figured out how to make those API calls. But I think it's worth mentioning that each request made to out API should not result in another request to the **Github API**. 

We could have the data stored locally (database? simple json file?) and add an endpoint to receive Github Webhooks. That way, whenever a user joins the org, a **Webhook** would be sent to our API, which would _only then_ make a request to the **Github API** to update the local data

**Comment by jbiers** [comment]
I wrote a piece of code that shows what I meant in the previous comment. Note that this is just an example and the functions which call the github API and save the file were not defined, think of them as abstractions for things we have already figured out how to do.

```go
package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
)

type WebhookPayload struct {
	Action string `json:"action"`
}

type TeamMembersResponse struct {
	TeamName     string   `json:"name"`
	MemberLogins []string `json:"members"`
}

func handleWebhook(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		w.WriteHeader(http.StatusMethodNotAllowed)

		return
	}

	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Println("Error reading request body:", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	var payload WebhookPayload
	err = json.Unmarshal(body, &payload)
	if err != nil {
		log.Println("Error parsing JSON payload:", err)
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	if payload.Action != "added" {
		w.WriteHeader(http.StatusOK)
		return
	}

	teamMembers, err := getOrganizationMembers("forjadev", "token_auth")
	if err != nil {
		log.Println("Error retrieving organization members:", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	err = saveTeamMembersToFile(teamMembers, "example_file.txt")
	if err != nil {
		log.Println("Error saving team members to file:", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusOK)
}

func main() {
	http.HandleFunc("/webhook", handleWebhook)
	http.ListenAndServe(":8080", nil)
}
```

**Comment by laracarvalho** [comment]
That seems like the best course of action that won't require many moving parts (database, cache). I suggest using a json file and making the API read directly from it. And to have a backup/fallback file if the webhook fails for some reason.
